name: CI/CD Pipeline

env:
  DB_DATABASE: pipeline
  DB_USERNAME: pipeline_user
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: 3306
  DB_DRIVER: mysql
  DB_NAMESPACE: Drupal\mysql\Driver\Database\mysql
  DB_AUTOLOAD: core/modules/mysql/src/Driver/Database/mysql/
  DB_ISOLATION_LEVEL: READ COMMITTED

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Drupal Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
  
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Configure .env File
        run: |
          cp .env.example .env
          sed -i 's|db_password|${{ secrets.DB_PASSWORD }}|' .env
          sed -i 's|db_host|${{ secrets.DB_HOST }}|' .env

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Verify Site is Running
        run: |
          ./vendor/bin/drush status || exit 1

      - name: Ping Home Page and Log HTML
        run: |
          php -S 127.0.0.1:8080 -t web > /dev/null 2>&1 &
          sleep 5
          curl -s http://127.0.0.1:8080/ || exit 1

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --configuration phpunit.xml --verbose

  measure:
    name: Run Lighthouse CI
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.14.x

      - name: Start PHP Server
        run: php -S 127.0.0.1:8080 -t web > server.log 2>&1 &

      - name: Wait for Server
        run: sleep 10

      - name: Run Lighthouse CI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  secure:
    name: Dependency Check
    runs-on: ubuntu-22.04
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable Dependabot Alerts
        uses: dependabot/fetch-metadata@v1

  # deploy:
  #   name: Deploy to Production
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Set up SSH
  #       uses: webfactory/ssh-agent@v0.7.0
  #       with:
  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  #     - name: Deploy via Rsync
  #       run: rsync -avz --delete ./ user@your-server:/path/to/project
