name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --configuration phpunit.xml --verbose

  measure:
    name: Run Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Install Lighthouse CLI
        run: npm install -g lighthouse puppeteer
  
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
  
      - name: Start PHP Server
        run: php -S localhost:8080 -t web &
  
      - name: Wait for Server
        run: sleep 5
  
      - name: Run Lighthouse
        run: lighthouse http://localhost:8080 --output=json --output-path=./lighthouse-report.json --chrome-flags="--headless --no-sandbox"
  
      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: ./lighthouse-report.json



  secure:
    name: Dependency Check
    runs-on: ubuntu-22.04
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable Dependabot Alerts
        uses: dependabot/fetch-metadata@v1

  # deploy:
  #   name: Deploy to Production
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Set up SSH
  #       uses: webfactory/ssh-agent@v0.7.0
  #       with:
  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  #     - name: Deploy via Rsync
  #       run: rsync -avz --delete ./ user@your-server:/path/to/project
